### PR TITLE
test(msm): ci test for msm benchmarks and correctness within proper time

### PR DESCRIPTION
**Pull request by moven0831**
# Issue
The current candidate choice for the MSM benchmarking test takes too long. Specifically, running the command below without the `--release` tag introduces significant time delays when generating the benchmarking instance:
```bash
cargo test --features=gpu-benchmarks test_benchmark_msm
```

# This PR
This PR introduces a lightweight benchmark test using smaller instances, specifically size of 2^10. This allows the tests to be completed within 60 seconds on M3 chips, even without the `--release` flag. Additionally, it includes a test to verify the correctness of the MSM results using both Arkworks built-in EC arithmetic and Arkworks MSM as the expected MSM result.

### Changes
- Benchmark Tests: Implement lightweight benchmark tests with smaller instances (2^10).
- Correctness Tests: Verify MSM results by comparing with Arkworks built-in EC arithmetic and Arkworks MSM.

# CI test command
For the the CI tests, use the following command:
```bash
cargo test --package mopro-core --features=gpu-benchmarks test_msm_correctness
```

### CODE REVIEW

**Comment by vivianjeng** [comment]
you can also add it in https://github.com/zkmopro/mopro/blob/main/.github/workflows/build-and-test.yml
🙏🏻

**Comment by FoodChain1028** [comment]
@moven0831 This command `cargo test --package mopro-core --features=gpu-benchmarks test_msm_correctness` would run 3 tests and the third one runs with a very long time. Is this normal?

```shell
running 3 tests
test middleware::gpu_explorations::arkworks_pippenger::tests::test_msm_correctness_small_sample ... ok
test middleware::gpu_explorations::metal::msm::tests::test_msm_correctness_small_sample ... ok
```

**Comment by moven0831** [comment]
> @moven0831 This command `cargo test --package mopro-core --features=gpu-benchmarks test_msm_correctness` would run 3 tests and the third one runs with a very long time. should we make the instance size smaller?
> 
> ```shell
> running 3 tests
> test middleware::gpu_explorations::arkworks_pippenger::tests::test_msm_correctness_small_sample ... ok
> test middleware::gpu_explorations::metal::msm::tests::test_msm_correctness_small_sample ... ok
> ```

I've adjusted the instance size from 2^10 to 2^8 and should be faster new. It takes nearly 70 sec to complete on my PC (M3 chip).

**Comment by vivianjeng** [comment]
I think you can try the macos machine
```yml
    gpu-benchmarks:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run GPU Benchmarks tests
              run: |
                  cd mopro-core
                  cargo test --features=gpu-benchmarks test_msm_correctness -- --nocapture
```

**Review by vivianjeng — APPROVED** [review]

**Pull request merged**
